/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  AdminNotifications: () => import('#controllers/admin_notifications_controller'),
  Agencies: () => import('#controllers/agencies_controller'),
  Cities: () => import('#controllers/cities_controller'),
  Clients: () => import('#controllers/clients_controller'),
  Invitations: () => import('#controllers/invitations_controller'),
  InvoicePayments: () => import('#controllers/invoice_payments_controller'),
  Invoices: () => import('#controllers/invoices_controller'),
  Maintenances: () => import('#controllers/maintenances_controller'),
  MarketplaceAuth: () => import('#controllers/marketplace_auth_controller'),
  MarketplaceBookings: () => import('#controllers/marketplace_bookings_controller'),
  MarketplaceCatalog: () => import('#controllers/marketplace_catalog_controller'),
  MarketplaceFavorite: () => import('#controllers/marketplace_favorite_controller'),
  MarketplacePublications: () => import('#controllers/marketplace_publications_controller'),
  MarketplaceReport: () => import('#controllers/marketplace_report_controller'),
  MarketplaceReview: () => import('#controllers/marketplace_review_controller'),
  Marques: () => import('#controllers/marques_controller'),
  Modeles: () => import('#controllers/modeles_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  OwnerPortal: () => import('#controllers/owner_portal_controller'),
  Owners: () => import('#controllers/owners_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Rentals: () => import('#controllers/rentals_controller'),
  Settings: () => import('#controllers/settings_controller'),
  VehicleExpenses: () => import('#controllers/vehicle_expenses_controller'),
  Vehicles: () => import('#controllers/vehicles_controller'),
}
