/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdminNotificationSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'href', 'id', 'meta', 'readAt', 'title', 'type', 'updatedAt', 'userId'] as const
  $columns = AdminNotificationSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare href: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare meta: any | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class AgencySchema extends BaseModel {
  static $columns = ['cityId', 'createdAt', 'id', 'isActive', 'isVerified', 'marketplacePublishBannedUntil', 'marketplaceRejectionStreak', 'name', 'notes', 'publishOnMarketplace', 'slug', 'updatedAt'] as const
  $columns = AgencySchema.$columns
  @column()
  declare cityId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare isVerified: boolean
  @column.dateTime()
  declare marketplacePublishBannedUntil: DateTime | null
  @column()
  declare marketplaceRejectionStreak: number
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare publishOnMarketplace: boolean
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CitySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'name', 'region', 'slug', 'updatedAt'] as const
  $columns = CitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare region: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClientAccountSchema extends BaseModel {
  static $columns = ['betterAuthUserId', 'clientId', 'createdAt', 'email', 'fullName', 'googleId', 'id', 'password', 'phone', 'status', 'updatedAt'] as const
  $columns = ClientAccountSchema.$columns
  @column()
  declare betterAuthUserId: string | null
  @column()
  declare clientId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare phone: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClientSchema extends BaseModel {
  static $columns = ['agencyId', 'birthDate', 'city', 'createdAt', 'email', 'fullName', 'id', 'idCardNumber', 'isActive', 'licenseExpiresAt', 'licenseNumber', 'licenseRectoPath', 'licenseVersoPath', 'notes', 'phone', 'source', 'type', 'updatedAt'] as const
  $columns = ClientSchema.$columns
  @column()
  declare agencyId: number | null
  @column.date()
  declare birthDate: DateTime | null
  @column()
  declare city: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idCardNumber: string | null
  @column()
  declare isActive: boolean
  @column.date()
  declare licenseExpiresAt: DateTime | null
  @column()
  declare licenseNumber: string | null
  @column()
  declare licenseRectoPath: string | null
  @column()
  declare licenseVersoPath: string | null
  @column()
  declare notes: string | null
  @column()
  declare phone: string
  @column()
  declare source: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InvoiceSchema extends BaseModel {
  static $columns = ['agencyId', 'amountHt', 'clientId', 'createdAt', 'description', 'id', 'issuedOn', 'rentalId', 'status', 'updatedAt'] as const
  $columns = InvoiceSchema.$columns
  @column()
  declare agencyId: number
  @column()
  declare amountHt: number
  @column()
  declare clientId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare issuedOn: DateTime
  @column()
  declare rentalId: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MaintenanceSchema extends BaseModel {
  static $columns = ['alertDays', 'cancelReason', 'cancelledAt', 'cancelledByUserId', 'cost', 'createdAt', 'description', 'id', 'mileage', 'nextDueOn', 'performedOn', 'provider', 'type', 'updatedAt', 'vehicleId'] as const
  $columns = MaintenanceSchema.$columns
  @column()
  declare alertDays: number
  @column()
  declare cancelReason: string | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare cancelledByUserId: number | null
  @column()
  declare cost: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mileage: number | null
  @column.date()
  declare nextDueOn: DateTime | null
  @column.date()
  declare performedOn: DateTime
  @column()
  declare provider: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleId: number
}

export class MarketplaceFavoriteSchema extends BaseModel {
  static $columns = ['clientAccountId', 'createdAt', 'id', 'notifiedAt', 'notifyAvailable', 'updatedAt', 'vehicleId'] as const
  $columns = MarketplaceFavoriteSchema.$columns
  @column()
  declare clientAccountId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare notifiedAt: DateTime | null
  @column()
  declare notifyAvailable: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleId: number
}

export class MarketplacePublicationEventSchema extends BaseModel {
  static $columns = ['action', 'actorUserId', 'agencyId', 'createdAt', 'id', 'reason', 'vehicleId'] as const
  $columns = MarketplacePublicationEventSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorUserId: number | null
  @column()
  declare agencyId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reason: string | null
  @column()
  declare vehicleId: number
}

export class MarketplaceReportSchema extends BaseModel {
  static $columns = ['agencyId', 'clientAccountId', 'contactEmail', 'createdAt', 'id', 'message', 'reason', 'rentalId', 'status', 'updatedAt', 'vehicleId'] as const
  $columns = MarketplaceReportSchema.$columns
  @column()
  declare agencyId: number
  @column()
  declare clientAccountId: number | null
  @column()
  declare contactEmail: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare message: string | null
  @column()
  declare reason: string
  @column()
  declare rentalId: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleId: number
}

export class MarketplaceReviewSchema extends BaseModel {
  static $columns = ['agencyId', 'cleanliness', 'clientId', 'comment', 'communication', 'createdAt', 'id', 'overallScore', 'punctuality', 'rentalId', 'status', 'updatedAt', 'vehicleCondition', 'vehicleId'] as const
  $columns = MarketplaceReviewSchema.$columns
  @column()
  declare agencyId: number
  @column()
  declare cleanliness: number
  @column()
  declare clientId: number
  @column()
  declare comment: string | null
  @column()
  declare communication: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare overallScore: string
  @column()
  declare punctuality: number
  @column()
  declare rentalId: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleCondition: number
  @column()
  declare vehicleId: number
}

export class MarqueSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = MarqueSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ModeleSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isActive', 'marqueId', 'name', 'updatedAt'] as const
  $columns = ModeleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare marqueId: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OwnerNotificationSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'href', 'id', 'meta', 'ownerId', 'readAt', 'title', 'type', 'updatedAt'] as const
  $columns = OwnerNotificationSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare href: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare meta: any | null
  @column()
  declare ownerId: number
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare title: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OwnerSchema extends BaseModel {
  static $columns = ['agencyId', 'city', 'createdAt', 'id', 'isActive', 'notes', 'phone', 'updatedAt', 'userId'] as const
  $columns = OwnerSchema.$columns
  @column()
  declare agencyId: number
  @column()
  declare city: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class PaymentSchema extends BaseModel {
  static $columns = ['amount', 'createdAt', 'id', 'invoiceId', 'method', 'notes', 'paidOn', 'reference', 'updatedAt'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare amount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceId: number
  @column()
  declare method: string | null
  @column()
  declare notes: string | null
  @column.date()
  declare paidOn: DateTime
  @column()
  declare reference: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RentalExtensionSchema extends BaseModel {
  static $columns = ['addedDays', 'amountHt', 'createdAt', 'createdByUserId', 'dailyPrice', 'id', 'newEndDate', 'notes', 'previousEndDate', 'rentalId', 'updatedAt'] as const
  $columns = RentalExtensionSchema.$columns
  @column()
  declare addedDays: number
  @column()
  declare amountHt: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column()
  declare dailyPrice: number
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare newEndDate: DateTime
  @column()
  declare notes: string | null
  @column.date()
  declare previousEndDate: DateTime
  @column()
  declare rentalId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RentalSchema extends BaseModel {
  static $columns = ['agencyId', 'amountPaid', 'cancelReason', 'cancelledAt', 'cancelledBy', 'clientId', 'createdAt', 'dailyPrice', 'endDate', 'id', 'notes', 'source', 'startDate', 'status', 'updatedAt', 'vehicleId'] as const
  $columns = RentalSchema.$columns
  @column()
  declare agencyId: number
  @column()
  declare amountPaid: number
  @column()
  declare cancelReason: string | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column()
  declare cancelledBy: string | null
  @column()
  declare clientId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dailyPrice: number
  @column.date()
  declare endDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare source: string
  @column.date()
  declare startDate: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleId: number
}

export class SettingSchema extends BaseModel {
  static $columns = ['agencyId', 'commissionPerDay', 'companyName', 'createdAt', 'depositAmount', 'id', 'rentalConditions', 'tvaRate', 'updatedAt'] as const
  $columns = SettingSchema.$columns
  @column()
  declare agencyId: number
  @column()
  declare commissionPerDay: number
  @column()
  declare companyName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare depositAmount: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rentalConditions: string | null
  @column()
  declare tvaRate: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['agencyId', 'createdAt', 'email', 'fullName', 'id', 'invitationExpiresAt', 'invitationToken', 'password', 'passwordSetAt', 'role', 'status', 'termsAcceptedAt', 'termsAcceptedIp', 'termsVersion', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare agencyId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare invitationExpiresAt: DateTime | null
  @column()
  declare invitationToken: string | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime()
  declare passwordSetAt: DateTime | null
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime()
  declare termsAcceptedAt: DateTime | null
  @column()
  declare termsAcceptedIp: string | null
  @column()
  declare termsVersion: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VehicleExpenseSchema extends BaseModel {
  static $columns = ['agencyId', 'amount', 'cancelReason', 'cancelledAt', 'createdAt', 'createdByUserId', 'id', 'notes', 'provider', 'spentOn', 'type', 'updatedAt', 'vehicleId'] as const
  $columns = VehicleExpenseSchema.$columns
  @column()
  declare agencyId: number
  @column()
  declare amount: number
  @column()
  declare cancelReason: string | null
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare notes: string | null
  @column()
  declare provider: string | null
  @column.date()
  declare spentOn: DateTime
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleId: number
}

export class VehiclePhotoSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'path', 'position', 'updatedAt', 'vehicleId'] as const
  $columns = VehiclePhotoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare path: string
  @column()
  declare position: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleId: number
}

export class VehicleSchema extends BaseModel {
  static $columns = ['agencyId', 'brand', 'color', 'complianceHold', 'createdAt', 'dailyPrice', 'fuel', 'id', 'insuranceAlertStage', 'insuranceCompany', 'insuranceExpiresAt', 'marketplaceIsRereview', 'marketplacePublicationStatus', 'marketplaceRejectionReason', 'marketplaceReviewedAt', 'marketplaceReviewedByUserId', 'marketplaceSubmittedAt', 'marqueId', 'mileage', 'model', 'modeleId', 'notes', 'ownerId', 'photoUrl', 'plate', 'status', 'technicalVisitAlertStage', 'technicalVisitAt', 'updatedAt', 'vehicleType', 'year'] as const
  $columns = VehicleSchema.$columns
  @column()
  declare agencyId: number
  @column()
  declare brand: string
  @column()
  declare color: string | null
  @column()
  declare complianceHold: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dailyPrice: number
  @column()
  declare fuel: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare insuranceAlertStage: string | null
  @column()
  declare insuranceCompany: string | null
  @column.date()
  declare insuranceExpiresAt: DateTime | null
  @column()
  declare marketplaceIsRereview: boolean
  @column()
  declare marketplacePublicationStatus: string
  @column()
  declare marketplaceRejectionReason: string | null
  @column.dateTime()
  declare marketplaceReviewedAt: DateTime | null
  @column()
  declare marketplaceReviewedByUserId: number | null
  @column.dateTime()
  declare marketplaceSubmittedAt: DateTime | null
  @column()
  declare marqueId: number | null
  @column()
  declare mileage: number
  @column()
  declare model: string
  @column()
  declare modeleId: number | null
  @column()
  declare notes: string | null
  @column()
  declare ownerId: number | null
  @column()
  declare photoUrl: string | null
  @column()
  declare plate: string
  @column()
  declare status: string
  @column()
  declare technicalVisitAlertStage: string | null
  @column.date()
  declare technicalVisitAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleType: string
  @column()
  declare year: number | null
}
