/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type AdminNotificationTransformer from '#transformers/admin_notification_transformer'
import type AgencyTransformer from '#transformers/agency_transformer'
import type CityTransformer from '#transformers/city_transformer'
import type ClientTransformer from '#transformers/client_transformer'
import type InvoiceTransformer from '#transformers/invoice_transformer'
import type MaintenanceTransformer from '#transformers/maintenance_transformer'
import type MarqueTransformer from '#transformers/marque_transformer'
import type ModeleTransformer from '#transformers/modele_transformer'
import type OwnerNotificationTransformer from '#transformers/owner_notification_transformer'
import type OwnerTransformer from '#transformers/owner_transformer'
import type PaymentTransformer from '#transformers/payment_transformer'
import type RentalTransformer from '#transformers/rental_transformer'
import type SettingTransformer from '#transformers/setting_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type VehicleExpenseTransformer from '#transformers/vehicle_expense_transformer'
import type VehicleTransformer from '#transformers/vehicle_transformer'

export namespace Data {
  export type AdminNotification = InferData<AdminNotificationTransformer>
  export namespace AdminNotification {
    export type Variants = InferVariants<AdminNotificationTransformer>
  }
  export type Agency = InferData<AgencyTransformer>
  export namespace Agency {
    export type Variants = InferVariants<AgencyTransformer>
  }
  export type City = InferData<CityTransformer>
  export namespace City {
    export type Variants = InferVariants<CityTransformer>
  }
  export type Client = InferData<ClientTransformer>
  export namespace Client {
    export type Variants = InferVariants<ClientTransformer>
  }
  export type Invoice = InferData<InvoiceTransformer>
  export namespace Invoice {
    export type Variants = InferVariants<InvoiceTransformer>
  }
  export type Maintenance = InferData<MaintenanceTransformer>
  export namespace Maintenance {
    export type Variants = InferVariants<MaintenanceTransformer>
  }
  export type Marque = InferData<MarqueTransformer>
  export namespace Marque {
    export type Variants = InferVariants<MarqueTransformer>
  }
  export type Modele = InferData<ModeleTransformer>
  export namespace Modele {
    export type Variants = InferVariants<ModeleTransformer>
  }
  export type OwnerNotification = InferData<OwnerNotificationTransformer>
  export namespace OwnerNotification {
    export type Variants = InferVariants<OwnerNotificationTransformer>
  }
  export type Owner = InferData<OwnerTransformer>
  export namespace Owner {
    export type Variants = InferVariants<OwnerTransformer>
  }
  export type Payment = InferData<PaymentTransformer>
  export namespace Payment {
    export type Variants = InferVariants<PaymentTransformer>
  }
  export type Rental = InferData<RentalTransformer>
  export namespace Rental {
    export type Variants = InferVariants<RentalTransformer>
  }
  export type Setting = InferData<SettingTransformer>
  export namespace Setting {
    export type Variants = InferVariants<SettingTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type VehicleExpense = InferData<VehicleExpenseTransformer>
  export namespace VehicleExpense {
    export type Variants = InferVariants<VehicleExpenseTransformer>
  }
  export type Vehicle = InferData<VehicleTransformer>
  export namespace Vehicle {
    export type Variants = InferVariants<VehicleTransformer>
  }
}
