/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.access_tokens.store': {
    methods: ["POST"],
    pattern: '/api/v1/auth/login',
    tokens: [{"old":"/api/v1/auth/login","type":0,"val":"api","end":""},{"old":"/api/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.access_tokens.store']['types'],
  },
  'invitations.invitations.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invitations/:token',
    tokens: [{"old":"/api/v1/invitations/:token","type":0,"val":"api","end":""},{"old":"/api/v1/invitations/:token","type":0,"val":"v1","end":""},{"old":"/api/v1/invitations/:token","type":0,"val":"invitations","end":""},{"old":"/api/v1/invitations/:token","type":1,"val":"token","end":""}],
    types: placeholder as Registry['invitations.invitations.show']['types'],
  },
  'invitations.invitations.accept': {
    methods: ["POST"],
    pattern: '/api/v1/invitations/:token/accept',
    tokens: [{"old":"/api/v1/invitations/:token/accept","type":0,"val":"api","end":""},{"old":"/api/v1/invitations/:token/accept","type":0,"val":"v1","end":""},{"old":"/api/v1/invitations/:token/accept","type":0,"val":"invitations","end":""},{"old":"/api/v1/invitations/:token/accept","type":1,"val":"token","end":""},{"old":"/api/v1/invitations/:token/accept","type":0,"val":"accept","end":""}],
    types: placeholder as Registry['invitations.invitations.accept']['types'],
  },
  'profile.profile.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/account/profile',
    tokens: [{"old":"/api/v1/account/profile","type":0,"val":"api","end":""},{"old":"/api/v1/account/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/account/profile","type":0,"val":"account","end":""},{"old":"/api/v1/account/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['profile.profile.show']['types'],
  },
  'profile.access_tokens.destroy': {
    methods: ["POST"],
    pattern: '/api/v1/account/logout',
    tokens: [{"old":"/api/v1/account/logout","type":0,"val":"api","end":""},{"old":"/api/v1/account/logout","type":0,"val":"v1","end":""},{"old":"/api/v1/account/logout","type":0,"val":"account","end":""},{"old":"/api/v1/account/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['profile.access_tokens.destroy']['types'],
  },
  'agencies.agencies.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/agencies',
    tokens: [{"old":"/api/v1/agencies","type":0,"val":"api","end":""},{"old":"/api/v1/agencies","type":0,"val":"v1","end":""},{"old":"/api/v1/agencies","type":0,"val":"agencies","end":""}],
    types: placeholder as Registry['agencies.agencies.index']['types'],
  },
  'agencies.agencies.store': {
    methods: ["POST"],
    pattern: '/api/v1/agencies',
    tokens: [{"old":"/api/v1/agencies","type":0,"val":"api","end":""},{"old":"/api/v1/agencies","type":0,"val":"v1","end":""},{"old":"/api/v1/agencies","type":0,"val":"agencies","end":""}],
    types: placeholder as Registry['agencies.agencies.store']['types'],
  },
  'agencies.agencies.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/agencies/:id',
    tokens: [{"old":"/api/v1/agencies/:id","type":0,"val":"api","end":""},{"old":"/api/v1/agencies/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/agencies/:id","type":0,"val":"agencies","end":""},{"old":"/api/v1/agencies/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['agencies.agencies.show']['types'],
  },
  'agencies.agencies.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/agencies/:id',
    tokens: [{"old":"/api/v1/agencies/:id","type":0,"val":"api","end":""},{"old":"/api/v1/agencies/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/agencies/:id","type":0,"val":"agencies","end":""},{"old":"/api/v1/agencies/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['agencies.agencies.update']['types'],
  },
  'agencies.agencies.invite_admin': {
    methods: ["POST"],
    pattern: '/api/v1/agencies/:id/admins',
    tokens: [{"old":"/api/v1/agencies/:id/admins","type":0,"val":"api","end":""},{"old":"/api/v1/agencies/:id/admins","type":0,"val":"v1","end":""},{"old":"/api/v1/agencies/:id/admins","type":0,"val":"agencies","end":""},{"old":"/api/v1/agencies/:id/admins","type":1,"val":"id","end":""},{"old":"/api/v1/agencies/:id/admins","type":0,"val":"admins","end":""}],
    types: placeholder as Registry['agencies.agencies.invite_admin']['types'],
  },
  'agencies.agencies.resend_admin_invitation': {
    methods: ["POST"],
    pattern: '/api/v1/agencies/:id/admins/:adminId/resend-invitation',
    tokens: [{"old":"/api/v1/agencies/:id/admins/:adminId/resend-invitation","type":0,"val":"api","end":""},{"old":"/api/v1/agencies/:id/admins/:adminId/resend-invitation","type":0,"val":"v1","end":""},{"old":"/api/v1/agencies/:id/admins/:adminId/resend-invitation","type":0,"val":"agencies","end":""},{"old":"/api/v1/agencies/:id/admins/:adminId/resend-invitation","type":1,"val":"id","end":""},{"old":"/api/v1/agencies/:id/admins/:adminId/resend-invitation","type":0,"val":"admins","end":""},{"old":"/api/v1/agencies/:id/admins/:adminId/resend-invitation","type":1,"val":"adminId","end":""},{"old":"/api/v1/agencies/:id/admins/:adminId/resend-invitation","type":0,"val":"resend-invitation","end":""}],
    types: placeholder as Registry['agencies.agencies.resend_admin_invitation']['types'],
  },
  'agencies.agencies.revoke_admin': {
    methods: ["DELETE"],
    pattern: '/api/v1/agencies/:id/admins/:adminId',
    tokens: [{"old":"/api/v1/agencies/:id/admins/:adminId","type":0,"val":"api","end":""},{"old":"/api/v1/agencies/:id/admins/:adminId","type":0,"val":"v1","end":""},{"old":"/api/v1/agencies/:id/admins/:adminId","type":0,"val":"agencies","end":""},{"old":"/api/v1/agencies/:id/admins/:adminId","type":1,"val":"id","end":""},{"old":"/api/v1/agencies/:id/admins/:adminId","type":0,"val":"admins","end":""},{"old":"/api/v1/agencies/:id/admins/:adminId","type":1,"val":"adminId","end":""}],
    types: placeholder as Registry['agencies.agencies.revoke_admin']['types'],
  },
  'marketplace_publications.marketplace_publications.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace-publications',
    tokens: [{"old":"/api/v1/marketplace-publications","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace-publications","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace-publications","type":0,"val":"marketplace-publications","end":""}],
    types: placeholder as Registry['marketplace_publications.marketplace_publications.index']['types'],
  },
  'marketplace_publications.marketplace_publications.agencies': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace-publications/agencies',
    tokens: [{"old":"/api/v1/marketplace-publications/agencies","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace-publications/agencies","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace-publications/agencies","type":0,"val":"marketplace-publications","end":""},{"old":"/api/v1/marketplace-publications/agencies","type":0,"val":"agencies","end":""}],
    types: placeholder as Registry['marketplace_publications.marketplace_publications.agencies']['types'],
  },
  'marketplace_publications.marketplace_publications.bulk_approve': {
    methods: ["POST"],
    pattern: '/api/v1/marketplace-publications/bulk-approve',
    tokens: [{"old":"/api/v1/marketplace-publications/bulk-approve","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace-publications/bulk-approve","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace-publications/bulk-approve","type":0,"val":"marketplace-publications","end":""},{"old":"/api/v1/marketplace-publications/bulk-approve","type":0,"val":"bulk-approve","end":""}],
    types: placeholder as Registry['marketplace_publications.marketplace_publications.bulk_approve']['types'],
  },
  'marketplace_publications.marketplace_publications.photo_file': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace-publications/:id/photos/:photoId',
    tokens: [{"old":"/api/v1/marketplace-publications/:id/photos/:photoId","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace-publications/:id/photos/:photoId","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace-publications/:id/photos/:photoId","type":0,"val":"marketplace-publications","end":""},{"old":"/api/v1/marketplace-publications/:id/photos/:photoId","type":1,"val":"id","end":""},{"old":"/api/v1/marketplace-publications/:id/photos/:photoId","type":0,"val":"photos","end":""},{"old":"/api/v1/marketplace-publications/:id/photos/:photoId","type":1,"val":"photoId","end":""}],
    types: placeholder as Registry['marketplace_publications.marketplace_publications.photo_file']['types'],
  },
  'marketplace_publications.marketplace_publications.history': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace-publications/:id/history',
    tokens: [{"old":"/api/v1/marketplace-publications/:id/history","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace-publications/:id/history","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace-publications/:id/history","type":0,"val":"marketplace-publications","end":""},{"old":"/api/v1/marketplace-publications/:id/history","type":1,"val":"id","end":""},{"old":"/api/v1/marketplace-publications/:id/history","type":0,"val":"history","end":""}],
    types: placeholder as Registry['marketplace_publications.marketplace_publications.history']['types'],
  },
  'marketplace_publications.marketplace_publications.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace-publications/:id',
    tokens: [{"old":"/api/v1/marketplace-publications/:id","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace-publications/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace-publications/:id","type":0,"val":"marketplace-publications","end":""},{"old":"/api/v1/marketplace-publications/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['marketplace_publications.marketplace_publications.show']['types'],
  },
  'marketplace_publications.marketplace_publications.approve': {
    methods: ["POST"],
    pattern: '/api/v1/marketplace-publications/:id/approve',
    tokens: [{"old":"/api/v1/marketplace-publications/:id/approve","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace-publications/:id/approve","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace-publications/:id/approve","type":0,"val":"marketplace-publications","end":""},{"old":"/api/v1/marketplace-publications/:id/approve","type":1,"val":"id","end":""},{"old":"/api/v1/marketplace-publications/:id/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['marketplace_publications.marketplace_publications.approve']['types'],
  },
  'marketplace_publications.marketplace_publications.reject': {
    methods: ["POST"],
    pattern: '/api/v1/marketplace-publications/:id/reject',
    tokens: [{"old":"/api/v1/marketplace-publications/:id/reject","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace-publications/:id/reject","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace-publications/:id/reject","type":0,"val":"marketplace-publications","end":""},{"old":"/api/v1/marketplace-publications/:id/reject","type":1,"val":"id","end":""},{"old":"/api/v1/marketplace-publications/:id/reject","type":0,"val":"reject","end":""}],
    types: placeholder as Registry['marketplace_publications.marketplace_publications.reject']['types'],
  },
  'marketplace_publications.marketplace_publications.unpublish': {
    methods: ["POST"],
    pattern: '/api/v1/marketplace-publications/:id/unpublish',
    tokens: [{"old":"/api/v1/marketplace-publications/:id/unpublish","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace-publications/:id/unpublish","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace-publications/:id/unpublish","type":0,"val":"marketplace-publications","end":""},{"old":"/api/v1/marketplace-publications/:id/unpublish","type":1,"val":"id","end":""},{"old":"/api/v1/marketplace-publications/:id/unpublish","type":0,"val":"unpublish","end":""}],
    types: placeholder as Registry['marketplace_publications.marketplace_publications.unpublish']['types'],
  },
  'marketplace_reports.marketplace_report.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace-reports',
    tokens: [{"old":"/api/v1/marketplace-reports","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace-reports","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace-reports","type":0,"val":"marketplace-reports","end":""}],
    types: placeholder as Registry['marketplace_reports.marketplace_report.index']['types'],
  },
  'owners.owners.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/owners',
    tokens: [{"old":"/api/v1/owners","type":0,"val":"api","end":""},{"old":"/api/v1/owners","type":0,"val":"v1","end":""},{"old":"/api/v1/owners","type":0,"val":"owners","end":""}],
    types: placeholder as Registry['owners.owners.index']['types'],
  },
  'owners.owners.store': {
    methods: ["POST"],
    pattern: '/api/v1/owners',
    tokens: [{"old":"/api/v1/owners","type":0,"val":"api","end":""},{"old":"/api/v1/owners","type":0,"val":"v1","end":""},{"old":"/api/v1/owners","type":0,"val":"owners","end":""}],
    types: placeholder as Registry['owners.owners.store']['types'],
  },
  'owners.owners.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/owners/:id',
    tokens: [{"old":"/api/v1/owners/:id","type":0,"val":"api","end":""},{"old":"/api/v1/owners/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/owners/:id","type":0,"val":"owners","end":""},{"old":"/api/v1/owners/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['owners.owners.show']['types'],
  },
  'owners.owners.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/owners/:id',
    tokens: [{"old":"/api/v1/owners/:id","type":0,"val":"api","end":""},{"old":"/api/v1/owners/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/owners/:id","type":0,"val":"owners","end":""},{"old":"/api/v1/owners/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['owners.owners.update']['types'],
  },
  'owners.owners.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/owners/:id',
    tokens: [{"old":"/api/v1/owners/:id","type":0,"val":"api","end":""},{"old":"/api/v1/owners/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/owners/:id","type":0,"val":"owners","end":""},{"old":"/api/v1/owners/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['owners.owners.destroy']['types'],
  },
  'owners.owners.resend_invitation': {
    methods: ["POST"],
    pattern: '/api/v1/owners/:id/resend-invitation',
    tokens: [{"old":"/api/v1/owners/:id/resend-invitation","type":0,"val":"api","end":""},{"old":"/api/v1/owners/:id/resend-invitation","type":0,"val":"v1","end":""},{"old":"/api/v1/owners/:id/resend-invitation","type":0,"val":"owners","end":""},{"old":"/api/v1/owners/:id/resend-invitation","type":1,"val":"id","end":""},{"old":"/api/v1/owners/:id/resend-invitation","type":0,"val":"resend-invitation","end":""}],
    types: placeholder as Registry['owners.owners.resend_invitation']['types'],
  },
  'marques.marques.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marques',
    tokens: [{"old":"/api/v1/marques","type":0,"val":"api","end":""},{"old":"/api/v1/marques","type":0,"val":"v1","end":""},{"old":"/api/v1/marques","type":0,"val":"marques","end":""}],
    types: placeholder as Registry['marques.marques.index']['types'],
  },
  'marques.marques.store': {
    methods: ["POST"],
    pattern: '/api/v1/marques',
    tokens: [{"old":"/api/v1/marques","type":0,"val":"api","end":""},{"old":"/api/v1/marques","type":0,"val":"v1","end":""},{"old":"/api/v1/marques","type":0,"val":"marques","end":""}],
    types: placeholder as Registry['marques.marques.store']['types'],
  },
  'marques.marques.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marques/:id',
    tokens: [{"old":"/api/v1/marques/:id","type":0,"val":"api","end":""},{"old":"/api/v1/marques/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/marques/:id","type":0,"val":"marques","end":""},{"old":"/api/v1/marques/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['marques.marques.show']['types'],
  },
  'modeles.modeles.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/modeles',
    tokens: [{"old":"/api/v1/modeles","type":0,"val":"api","end":""},{"old":"/api/v1/modeles","type":0,"val":"v1","end":""},{"old":"/api/v1/modeles","type":0,"val":"modeles","end":""}],
    types: placeholder as Registry['modeles.modeles.index']['types'],
  },
  'modeles.modeles.store': {
    methods: ["POST"],
    pattern: '/api/v1/modeles',
    tokens: [{"old":"/api/v1/modeles","type":0,"val":"api","end":""},{"old":"/api/v1/modeles","type":0,"val":"v1","end":""},{"old":"/api/v1/modeles","type":0,"val":"modeles","end":""}],
    types: placeholder as Registry['modeles.modeles.store']['types'],
  },
  'vehicles.vehicles.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/vehicles',
    tokens: [{"old":"/api/v1/vehicles","type":0,"val":"api","end":""},{"old":"/api/v1/vehicles","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicles","type":0,"val":"vehicles","end":""}],
    types: placeholder as Registry['vehicles.vehicles.index']['types'],
  },
  'vehicles.vehicles.store': {
    methods: ["POST"],
    pattern: '/api/v1/vehicles',
    tokens: [{"old":"/api/v1/vehicles","type":0,"val":"api","end":""},{"old":"/api/v1/vehicles","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicles","type":0,"val":"vehicles","end":""}],
    types: placeholder as Registry['vehicles.vehicles.store']['types'],
  },
  'vehicles.vehicles.expenses': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/vehicles/:id/expenses',
    tokens: [{"old":"/api/v1/vehicles/:id/expenses","type":0,"val":"api","end":""},{"old":"/api/v1/vehicles/:id/expenses","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicles/:id/expenses","type":0,"val":"vehicles","end":""},{"old":"/api/v1/vehicles/:id/expenses","type":1,"val":"id","end":""},{"old":"/api/v1/vehicles/:id/expenses","type":0,"val":"expenses","end":""}],
    types: placeholder as Registry['vehicles.vehicles.expenses']['types'],
  },
  'vehicles.vehicles.summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/vehicles/:id/summary',
    tokens: [{"old":"/api/v1/vehicles/:id/summary","type":0,"val":"api","end":""},{"old":"/api/v1/vehicles/:id/summary","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicles/:id/summary","type":0,"val":"vehicles","end":""},{"old":"/api/v1/vehicles/:id/summary","type":1,"val":"id","end":""},{"old":"/api/v1/vehicles/:id/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['vehicles.vehicles.summary']['types'],
  },
  'vehicles.vehicles.upload_photos': {
    methods: ["POST"],
    pattern: '/api/v1/vehicles/:id/photos',
    tokens: [{"old":"/api/v1/vehicles/:id/photos","type":0,"val":"api","end":""},{"old":"/api/v1/vehicles/:id/photos","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicles/:id/photos","type":0,"val":"vehicles","end":""},{"old":"/api/v1/vehicles/:id/photos","type":1,"val":"id","end":""},{"old":"/api/v1/vehicles/:id/photos","type":0,"val":"photos","end":""}],
    types: placeholder as Registry['vehicles.vehicles.upload_photos']['types'],
  },
  'vehicles.vehicles.photo_file': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/vehicles/:id/photos/:photoId',
    tokens: [{"old":"/api/v1/vehicles/:id/photos/:photoId","type":0,"val":"api","end":""},{"old":"/api/v1/vehicles/:id/photos/:photoId","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicles/:id/photos/:photoId","type":0,"val":"vehicles","end":""},{"old":"/api/v1/vehicles/:id/photos/:photoId","type":1,"val":"id","end":""},{"old":"/api/v1/vehicles/:id/photos/:photoId","type":0,"val":"photos","end":""},{"old":"/api/v1/vehicles/:id/photos/:photoId","type":1,"val":"photoId","end":""}],
    types: placeholder as Registry['vehicles.vehicles.photo_file']['types'],
  },
  'vehicles.vehicles.destroy_photo': {
    methods: ["DELETE"],
    pattern: '/api/v1/vehicles/:id/photos/:photoId',
    tokens: [{"old":"/api/v1/vehicles/:id/photos/:photoId","type":0,"val":"api","end":""},{"old":"/api/v1/vehicles/:id/photos/:photoId","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicles/:id/photos/:photoId","type":0,"val":"vehicles","end":""},{"old":"/api/v1/vehicles/:id/photos/:photoId","type":1,"val":"id","end":""},{"old":"/api/v1/vehicles/:id/photos/:photoId","type":0,"val":"photos","end":""},{"old":"/api/v1/vehicles/:id/photos/:photoId","type":1,"val":"photoId","end":""}],
    types: placeholder as Registry['vehicles.vehicles.destroy_photo']['types'],
  },
  'vehicles.vehicles.submit_marketplace': {
    methods: ["POST"],
    pattern: '/api/v1/vehicles/:id/marketplace/submit',
    tokens: [{"old":"/api/v1/vehicles/:id/marketplace/submit","type":0,"val":"api","end":""},{"old":"/api/v1/vehicles/:id/marketplace/submit","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicles/:id/marketplace/submit","type":0,"val":"vehicles","end":""},{"old":"/api/v1/vehicles/:id/marketplace/submit","type":1,"val":"id","end":""},{"old":"/api/v1/vehicles/:id/marketplace/submit","type":0,"val":"marketplace","end":""},{"old":"/api/v1/vehicles/:id/marketplace/submit","type":0,"val":"submit","end":""}],
    types: placeholder as Registry['vehicles.vehicles.submit_marketplace']['types'],
  },
  'vehicles.vehicles.unpublish_marketplace': {
    methods: ["POST"],
    pattern: '/api/v1/vehicles/:id/marketplace/unpublish',
    tokens: [{"old":"/api/v1/vehicles/:id/marketplace/unpublish","type":0,"val":"api","end":""},{"old":"/api/v1/vehicles/:id/marketplace/unpublish","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicles/:id/marketplace/unpublish","type":0,"val":"vehicles","end":""},{"old":"/api/v1/vehicles/:id/marketplace/unpublish","type":1,"val":"id","end":""},{"old":"/api/v1/vehicles/:id/marketplace/unpublish","type":0,"val":"marketplace","end":""},{"old":"/api/v1/vehicles/:id/marketplace/unpublish","type":0,"val":"unpublish","end":""}],
    types: placeholder as Registry['vehicles.vehicles.unpublish_marketplace']['types'],
  },
  'vehicles.vehicles.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/vehicles/:id',
    tokens: [{"old":"/api/v1/vehicles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/vehicles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicles/:id","type":0,"val":"vehicles","end":""},{"old":"/api/v1/vehicles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['vehicles.vehicles.show']['types'],
  },
  'vehicles.vehicles.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/vehicles/:id',
    tokens: [{"old":"/api/v1/vehicles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/vehicles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicles/:id","type":0,"val":"vehicles","end":""},{"old":"/api/v1/vehicles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['vehicles.vehicles.update']['types'],
  },
  'vehicles.vehicles.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/vehicles/:id',
    tokens: [{"old":"/api/v1/vehicles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/vehicles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicles/:id","type":0,"val":"vehicles","end":""},{"old":"/api/v1/vehicles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['vehicles.vehicles.destroy']['types'],
  },
  'vehicle_expenses.vehicle_expenses.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/vehicle-expenses',
    tokens: [{"old":"/api/v1/vehicle-expenses","type":0,"val":"api","end":""},{"old":"/api/v1/vehicle-expenses","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicle-expenses","type":0,"val":"vehicle-expenses","end":""}],
    types: placeholder as Registry['vehicle_expenses.vehicle_expenses.index']['types'],
  },
  'vehicle_expenses.vehicle_expenses.store': {
    methods: ["POST"],
    pattern: '/api/v1/vehicle-expenses',
    tokens: [{"old":"/api/v1/vehicle-expenses","type":0,"val":"api","end":""},{"old":"/api/v1/vehicle-expenses","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicle-expenses","type":0,"val":"vehicle-expenses","end":""}],
    types: placeholder as Registry['vehicle_expenses.vehicle_expenses.store']['types'],
  },
  'vehicle_expenses.vehicle_expenses.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/vehicle-expenses/:id',
    tokens: [{"old":"/api/v1/vehicle-expenses/:id","type":0,"val":"api","end":""},{"old":"/api/v1/vehicle-expenses/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicle-expenses/:id","type":0,"val":"vehicle-expenses","end":""},{"old":"/api/v1/vehicle-expenses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['vehicle_expenses.vehicle_expenses.show']['types'],
  },
  'vehicle_expenses.vehicle_expenses.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/vehicle-expenses/:id',
    tokens: [{"old":"/api/v1/vehicle-expenses/:id","type":0,"val":"api","end":""},{"old":"/api/v1/vehicle-expenses/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicle-expenses/:id","type":0,"val":"vehicle-expenses","end":""},{"old":"/api/v1/vehicle-expenses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['vehicle_expenses.vehicle_expenses.update']['types'],
  },
  'vehicle_expenses.vehicle_expenses.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/vehicle-expenses/:id',
    tokens: [{"old":"/api/v1/vehicle-expenses/:id","type":0,"val":"api","end":""},{"old":"/api/v1/vehicle-expenses/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/vehicle-expenses/:id","type":0,"val":"vehicle-expenses","end":""},{"old":"/api/v1/vehicle-expenses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['vehicle_expenses.vehicle_expenses.destroy']['types'],
  },
  'clients.clients.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/clients',
    tokens: [{"old":"/api/v1/clients","type":0,"val":"api","end":""},{"old":"/api/v1/clients","type":0,"val":"v1","end":""},{"old":"/api/v1/clients","type":0,"val":"clients","end":""}],
    types: placeholder as Registry['clients.clients.index']['types'],
  },
  'clients.clients.store': {
    methods: ["POST"],
    pattern: '/api/v1/clients',
    tokens: [{"old":"/api/v1/clients","type":0,"val":"api","end":""},{"old":"/api/v1/clients","type":0,"val":"v1","end":""},{"old":"/api/v1/clients","type":0,"val":"clients","end":""}],
    types: placeholder as Registry['clients.clients.store']['types'],
  },
  'clients.clients.upload_license': {
    methods: ["POST"],
    pattern: '/api/v1/clients/:id/license',
    tokens: [{"old":"/api/v1/clients/:id/license","type":0,"val":"api","end":""},{"old":"/api/v1/clients/:id/license","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/:id/license","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/:id/license","type":1,"val":"id","end":""},{"old":"/api/v1/clients/:id/license","type":0,"val":"license","end":""}],
    types: placeholder as Registry['clients.clients.upload_license']['types'],
  },
  'clients.clients.license_file': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/clients/:id/license/:side',
    tokens: [{"old":"/api/v1/clients/:id/license/:side","type":0,"val":"api","end":""},{"old":"/api/v1/clients/:id/license/:side","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/:id/license/:side","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/:id/license/:side","type":1,"val":"id","end":""},{"old":"/api/v1/clients/:id/license/:side","type":0,"val":"license","end":""},{"old":"/api/v1/clients/:id/license/:side","type":1,"val":"side","end":""}],
    types: placeholder as Registry['clients.clients.license_file']['types'],
  },
  'clients.clients.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/clients/:id',
    tokens: [{"old":"/api/v1/clients/:id","type":0,"val":"api","end":""},{"old":"/api/v1/clients/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/:id","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['clients.clients.show']['types'],
  },
  'clients.clients.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/clients/:id',
    tokens: [{"old":"/api/v1/clients/:id","type":0,"val":"api","end":""},{"old":"/api/v1/clients/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/:id","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['clients.clients.update']['types'],
  },
  'clients.clients.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/clients/:id',
    tokens: [{"old":"/api/v1/clients/:id","type":0,"val":"api","end":""},{"old":"/api/v1/clients/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/clients/:id","type":0,"val":"clients","end":""},{"old":"/api/v1/clients/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['clients.clients.destroy']['types'],
  },
  'rentals.rentals.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/rentals',
    tokens: [{"old":"/api/v1/rentals","type":0,"val":"api","end":""},{"old":"/api/v1/rentals","type":0,"val":"v1","end":""},{"old":"/api/v1/rentals","type":0,"val":"rentals","end":""}],
    types: placeholder as Registry['rentals.rentals.index']['types'],
  },
  'rentals.rentals.store': {
    methods: ["POST"],
    pattern: '/api/v1/rentals',
    tokens: [{"old":"/api/v1/rentals","type":0,"val":"api","end":""},{"old":"/api/v1/rentals","type":0,"val":"v1","end":""},{"old":"/api/v1/rentals","type":0,"val":"rentals","end":""}],
    types: placeholder as Registry['rentals.rentals.store']['types'],
  },
  'rentals.rentals.contract': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/rentals/:id/contract',
    tokens: [{"old":"/api/v1/rentals/:id/contract","type":0,"val":"api","end":""},{"old":"/api/v1/rentals/:id/contract","type":0,"val":"v1","end":""},{"old":"/api/v1/rentals/:id/contract","type":0,"val":"rentals","end":""},{"old":"/api/v1/rentals/:id/contract","type":1,"val":"id","end":""},{"old":"/api/v1/rentals/:id/contract","type":0,"val":"contract","end":""}],
    types: placeholder as Registry['rentals.rentals.contract']['types'],
  },
  'rentals.rentals.extend': {
    methods: ["POST"],
    pattern: '/api/v1/rentals/:id/extend',
    tokens: [{"old":"/api/v1/rentals/:id/extend","type":0,"val":"api","end":""},{"old":"/api/v1/rentals/:id/extend","type":0,"val":"v1","end":""},{"old":"/api/v1/rentals/:id/extend","type":0,"val":"rentals","end":""},{"old":"/api/v1/rentals/:id/extend","type":1,"val":"id","end":""},{"old":"/api/v1/rentals/:id/extend","type":0,"val":"extend","end":""}],
    types: placeholder as Registry['rentals.rentals.extend']['types'],
  },
  'rentals.rentals.approve': {
    methods: ["POST"],
    pattern: '/api/v1/rentals/:id/approve',
    tokens: [{"old":"/api/v1/rentals/:id/approve","type":0,"val":"api","end":""},{"old":"/api/v1/rentals/:id/approve","type":0,"val":"v1","end":""},{"old":"/api/v1/rentals/:id/approve","type":0,"val":"rentals","end":""},{"old":"/api/v1/rentals/:id/approve","type":1,"val":"id","end":""},{"old":"/api/v1/rentals/:id/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['rentals.rentals.approve']['types'],
  },
  'rentals.rentals.reject': {
    methods: ["POST"],
    pattern: '/api/v1/rentals/:id/reject',
    tokens: [{"old":"/api/v1/rentals/:id/reject","type":0,"val":"api","end":""},{"old":"/api/v1/rentals/:id/reject","type":0,"val":"v1","end":""},{"old":"/api/v1/rentals/:id/reject","type":0,"val":"rentals","end":""},{"old":"/api/v1/rentals/:id/reject","type":1,"val":"id","end":""},{"old":"/api/v1/rentals/:id/reject","type":0,"val":"reject","end":""}],
    types: placeholder as Registry['rentals.rentals.reject']['types'],
  },
  'rentals.rentals.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/rentals/:id',
    tokens: [{"old":"/api/v1/rentals/:id","type":0,"val":"api","end":""},{"old":"/api/v1/rentals/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/rentals/:id","type":0,"val":"rentals","end":""},{"old":"/api/v1/rentals/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rentals.rentals.show']['types'],
  },
  'rentals.rentals.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/rentals/:id',
    tokens: [{"old":"/api/v1/rentals/:id","type":0,"val":"api","end":""},{"old":"/api/v1/rentals/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/rentals/:id","type":0,"val":"rentals","end":""},{"old":"/api/v1/rentals/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rentals.rentals.update']['types'],
  },
  'rentals.rentals.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/rentals/:id',
    tokens: [{"old":"/api/v1/rentals/:id","type":0,"val":"api","end":""},{"old":"/api/v1/rentals/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/rentals/:id","type":0,"val":"rentals","end":""},{"old":"/api/v1/rentals/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['rentals.rentals.destroy']['types'],
  },
  'invoices.invoices.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invoices',
    tokens: [{"old":"/api/v1/invoices","type":0,"val":"api","end":""},{"old":"/api/v1/invoices","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoices.invoices.index']['types'],
  },
  'invoices.invoices.store': {
    methods: ["POST"],
    pattern: '/api/v1/invoices',
    tokens: [{"old":"/api/v1/invoices","type":0,"val":"api","end":""},{"old":"/api/v1/invoices","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['invoices.invoices.store']['types'],
  },
  'invoices.invoice_payments.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invoices/:invoiceId/payments',
    tokens: [{"old":"/api/v1/invoices/:invoiceId/payments","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:invoiceId/payments","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:invoiceId/payments","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:invoiceId/payments","type":1,"val":"invoiceId","end":""},{"old":"/api/v1/invoices/:invoiceId/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['invoices.invoice_payments.index']['types'],
  },
  'invoices.invoice_payments.store': {
    methods: ["POST"],
    pattern: '/api/v1/invoices/:invoiceId/payments',
    tokens: [{"old":"/api/v1/invoices/:invoiceId/payments","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:invoiceId/payments","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:invoiceId/payments","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:invoiceId/payments","type":1,"val":"invoiceId","end":""},{"old":"/api/v1/invoices/:invoiceId/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['invoices.invoice_payments.store']['types'],
  },
  'invoices.invoice_payments.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/invoices/:invoiceId/payments/:paymentId',
    tokens: [{"old":"/api/v1/invoices/:invoiceId/payments/:paymentId","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:invoiceId/payments/:paymentId","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:invoiceId/payments/:paymentId","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:invoiceId/payments/:paymentId","type":1,"val":"invoiceId","end":""},{"old":"/api/v1/invoices/:invoiceId/payments/:paymentId","type":0,"val":"payments","end":""},{"old":"/api/v1/invoices/:invoiceId/payments/:paymentId","type":1,"val":"paymentId","end":""}],
    types: placeholder as Registry['invoices.invoice_payments.destroy']['types'],
  },
  'invoices.invoices.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/invoices/:id',
    tokens: [{"old":"/api/v1/invoices/:id","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invoices.invoices.show']['types'],
  },
  'invoices.invoices.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/invoices/:id',
    tokens: [{"old":"/api/v1/invoices/:id","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invoices.invoices.update']['types'],
  },
  'invoices.invoices.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/invoices/:id',
    tokens: [{"old":"/api/v1/invoices/:id","type":0,"val":"api","end":""},{"old":"/api/v1/invoices/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/invoices/:id","type":0,"val":"invoices","end":""},{"old":"/api/v1/invoices/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['invoices.invoices.destroy']['types'],
  },
  'maintenances.maintenances.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/maintenances',
    tokens: [{"old":"/api/v1/maintenances","type":0,"val":"api","end":""},{"old":"/api/v1/maintenances","type":0,"val":"v1","end":""},{"old":"/api/v1/maintenances","type":0,"val":"maintenances","end":""}],
    types: placeholder as Registry['maintenances.maintenances.index']['types'],
  },
  'maintenances.maintenances.store': {
    methods: ["POST"],
    pattern: '/api/v1/maintenances',
    tokens: [{"old":"/api/v1/maintenances","type":0,"val":"api","end":""},{"old":"/api/v1/maintenances","type":0,"val":"v1","end":""},{"old":"/api/v1/maintenances","type":0,"val":"maintenances","end":""}],
    types: placeholder as Registry['maintenances.maintenances.store']['types'],
  },
  'maintenances.maintenances.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/maintenances/:id',
    tokens: [{"old":"/api/v1/maintenances/:id","type":0,"val":"api","end":""},{"old":"/api/v1/maintenances/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/maintenances/:id","type":0,"val":"maintenances","end":""},{"old":"/api/v1/maintenances/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['maintenances.maintenances.show']['types'],
  },
  'maintenances.maintenances.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/maintenances/:id',
    tokens: [{"old":"/api/v1/maintenances/:id","type":0,"val":"api","end":""},{"old":"/api/v1/maintenances/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/maintenances/:id","type":0,"val":"maintenances","end":""},{"old":"/api/v1/maintenances/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['maintenances.maintenances.update']['types'],
  },
  'maintenances.maintenances.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/maintenances/:id',
    tokens: [{"old":"/api/v1/maintenances/:id","type":0,"val":"api","end":""},{"old":"/api/v1/maintenances/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/maintenances/:id","type":0,"val":"maintenances","end":""},{"old":"/api/v1/maintenances/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['maintenances.maintenances.destroy']['types'],
  },
  'settings.settings.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/settings',
    tokens: [{"old":"/api/v1/settings","type":0,"val":"api","end":""},{"old":"/api/v1/settings","type":0,"val":"v1","end":""},{"old":"/api/v1/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.settings.show']['types'],
  },
  'settings.settings.update': {
    methods: ["PATCH"],
    pattern: '/api/v1/settings',
    tokens: [{"old":"/api/v1/settings","type":0,"val":"api","end":""},{"old":"/api/v1/settings","type":0,"val":"v1","end":""},{"old":"/api/v1/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.settings.update']['types'],
  },
  'admin_notifications.admin_notifications.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin-notifications',
    tokens: [{"old":"/api/v1/admin-notifications","type":0,"val":"api","end":""},{"old":"/api/v1/admin-notifications","type":0,"val":"v1","end":""},{"old":"/api/v1/admin-notifications","type":0,"val":"admin-notifications","end":""}],
    types: placeholder as Registry['admin_notifications.admin_notifications.index']['types'],
  },
  'admin_notifications.admin_notifications.unread_count': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/admin-notifications/unread-count',
    tokens: [{"old":"/api/v1/admin-notifications/unread-count","type":0,"val":"api","end":""},{"old":"/api/v1/admin-notifications/unread-count","type":0,"val":"v1","end":""},{"old":"/api/v1/admin-notifications/unread-count","type":0,"val":"admin-notifications","end":""},{"old":"/api/v1/admin-notifications/unread-count","type":0,"val":"unread-count","end":""}],
    types: placeholder as Registry['admin_notifications.admin_notifications.unread_count']['types'],
  },
  'admin_notifications.admin_notifications.mark_read': {
    methods: ["PATCH"],
    pattern: '/api/v1/admin-notifications/:id/read',
    tokens: [{"old":"/api/v1/admin-notifications/:id/read","type":0,"val":"api","end":""},{"old":"/api/v1/admin-notifications/:id/read","type":0,"val":"v1","end":""},{"old":"/api/v1/admin-notifications/:id/read","type":0,"val":"admin-notifications","end":""},{"old":"/api/v1/admin-notifications/:id/read","type":1,"val":"id","end":""},{"old":"/api/v1/admin-notifications/:id/read","type":0,"val":"read","end":""}],
    types: placeholder as Registry['admin_notifications.admin_notifications.mark_read']['types'],
  },
  'admin_notifications.admin_notifications.mark_all_read': {
    methods: ["POST"],
    pattern: '/api/v1/admin-notifications/read-all',
    tokens: [{"old":"/api/v1/admin-notifications/read-all","type":0,"val":"api","end":""},{"old":"/api/v1/admin-notifications/read-all","type":0,"val":"v1","end":""},{"old":"/api/v1/admin-notifications/read-all","type":0,"val":"admin-notifications","end":""},{"old":"/api/v1/admin-notifications/read-all","type":0,"val":"read-all","end":""}],
    types: placeholder as Registry['admin_notifications.admin_notifications.mark_all_read']['types'],
  },
  'owner_portal.owner_portal.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/owner/dashboard',
    tokens: [{"old":"/api/v1/owner/dashboard","type":0,"val":"api","end":""},{"old":"/api/v1/owner/dashboard","type":0,"val":"v1","end":""},{"old":"/api/v1/owner/dashboard","type":0,"val":"owner","end":""},{"old":"/api/v1/owner/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['owner_portal.owner_portal.dashboard']['types'],
  },
  'owner_portal.owner_portal.vehicles': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/owner/vehicles',
    tokens: [{"old":"/api/v1/owner/vehicles","type":0,"val":"api","end":""},{"old":"/api/v1/owner/vehicles","type":0,"val":"v1","end":""},{"old":"/api/v1/owner/vehicles","type":0,"val":"owner","end":""},{"old":"/api/v1/owner/vehicles","type":0,"val":"vehicles","end":""}],
    types: placeholder as Registry['owner_portal.owner_portal.vehicles']['types'],
  },
  'owner_portal.owner_portal.vehicle_expenses': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/owner/vehicles/:id/expenses',
    tokens: [{"old":"/api/v1/owner/vehicles/:id/expenses","type":0,"val":"api","end":""},{"old":"/api/v1/owner/vehicles/:id/expenses","type":0,"val":"v1","end":""},{"old":"/api/v1/owner/vehicles/:id/expenses","type":0,"val":"owner","end":""},{"old":"/api/v1/owner/vehicles/:id/expenses","type":0,"val":"vehicles","end":""},{"old":"/api/v1/owner/vehicles/:id/expenses","type":1,"val":"id","end":""},{"old":"/api/v1/owner/vehicles/:id/expenses","type":0,"val":"expenses","end":""}],
    types: placeholder as Registry['owner_portal.owner_portal.vehicle_expenses']['types'],
  },
  'owner_portal.owner_portal.vehicle_summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/owner/vehicles/:id/summary',
    tokens: [{"old":"/api/v1/owner/vehicles/:id/summary","type":0,"val":"api","end":""},{"old":"/api/v1/owner/vehicles/:id/summary","type":0,"val":"v1","end":""},{"old":"/api/v1/owner/vehicles/:id/summary","type":0,"val":"owner","end":""},{"old":"/api/v1/owner/vehicles/:id/summary","type":0,"val":"vehicles","end":""},{"old":"/api/v1/owner/vehicles/:id/summary","type":1,"val":"id","end":""},{"old":"/api/v1/owner/vehicles/:id/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['owner_portal.owner_portal.vehicle_summary']['types'],
  },
  'owner_portal.owner_portal.vehicle': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/owner/vehicles/:id',
    tokens: [{"old":"/api/v1/owner/vehicles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/owner/vehicles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/owner/vehicles/:id","type":0,"val":"owner","end":""},{"old":"/api/v1/owner/vehicles/:id","type":0,"val":"vehicles","end":""},{"old":"/api/v1/owner/vehicles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['owner_portal.owner_portal.vehicle']['types'],
  },
  'owner_portal.owner_portal.rentals': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/owner/rentals',
    tokens: [{"old":"/api/v1/owner/rentals","type":0,"val":"api","end":""},{"old":"/api/v1/owner/rentals","type":0,"val":"v1","end":""},{"old":"/api/v1/owner/rentals","type":0,"val":"owner","end":""},{"old":"/api/v1/owner/rentals","type":0,"val":"rentals","end":""}],
    types: placeholder as Registry['owner_portal.owner_portal.rentals']['types'],
  },
  'owner_portal.owner_portal.revenues': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/owner/revenues',
    tokens: [{"old":"/api/v1/owner/revenues","type":0,"val":"api","end":""},{"old":"/api/v1/owner/revenues","type":0,"val":"v1","end":""},{"old":"/api/v1/owner/revenues","type":0,"val":"owner","end":""},{"old":"/api/v1/owner/revenues","type":0,"val":"revenues","end":""}],
    types: placeholder as Registry['owner_portal.owner_portal.revenues']['types'],
  },
  'owner_portal.owner_portal.notifications': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/owner/notifications',
    tokens: [{"old":"/api/v1/owner/notifications","type":0,"val":"api","end":""},{"old":"/api/v1/owner/notifications","type":0,"val":"v1","end":""},{"old":"/api/v1/owner/notifications","type":0,"val":"owner","end":""},{"old":"/api/v1/owner/notifications","type":0,"val":"notifications","end":""}],
    types: placeholder as Registry['owner_portal.owner_portal.notifications']['types'],
  },
  'owner_portal.owner_portal.notifications_unread_count': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/owner/notifications/unread-count',
    tokens: [{"old":"/api/v1/owner/notifications/unread-count","type":0,"val":"api","end":""},{"old":"/api/v1/owner/notifications/unread-count","type":0,"val":"v1","end":""},{"old":"/api/v1/owner/notifications/unread-count","type":0,"val":"owner","end":""},{"old":"/api/v1/owner/notifications/unread-count","type":0,"val":"notifications","end":""},{"old":"/api/v1/owner/notifications/unread-count","type":0,"val":"unread-count","end":""}],
    types: placeholder as Registry['owner_portal.owner_portal.notifications_unread_count']['types'],
  },
  'owner_portal.owner_portal.mark_notification_read': {
    methods: ["PATCH"],
    pattern: '/api/v1/owner/notifications/:id/read',
    tokens: [{"old":"/api/v1/owner/notifications/:id/read","type":0,"val":"api","end":""},{"old":"/api/v1/owner/notifications/:id/read","type":0,"val":"v1","end":""},{"old":"/api/v1/owner/notifications/:id/read","type":0,"val":"owner","end":""},{"old":"/api/v1/owner/notifications/:id/read","type":0,"val":"notifications","end":""},{"old":"/api/v1/owner/notifications/:id/read","type":1,"val":"id","end":""},{"old":"/api/v1/owner/notifications/:id/read","type":0,"val":"read","end":""}],
    types: placeholder as Registry['owner_portal.owner_portal.mark_notification_read']['types'],
  },
  'owner_portal.owner_portal.mark_all_notifications_read': {
    methods: ["POST"],
    pattern: '/api/v1/owner/notifications/read-all',
    tokens: [{"old":"/api/v1/owner/notifications/read-all","type":0,"val":"api","end":""},{"old":"/api/v1/owner/notifications/read-all","type":0,"val":"v1","end":""},{"old":"/api/v1/owner/notifications/read-all","type":0,"val":"owner","end":""},{"old":"/api/v1/owner/notifications/read-all","type":0,"val":"notifications","end":""},{"old":"/api/v1/owner/notifications/read-all","type":0,"val":"read-all","end":""}],
    types: placeholder as Registry['owner_portal.owner_portal.mark_all_notifications_read']['types'],
  },
  'marketplace.marketplace_catalog.cities': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace/cities',
    tokens: [{"old":"/api/v1/marketplace/cities","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/cities","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/cities","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/cities","type":0,"val":"cities","end":""}],
    types: placeholder as Registry['marketplace.marketplace_catalog.cities']['types'],
  },
  'marketplace.marketplace_catalog.vehicles': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace/vehicles',
    tokens: [{"old":"/api/v1/marketplace/vehicles","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/vehicles","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/vehicles","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/vehicles","type":0,"val":"vehicles","end":""}],
    types: placeholder as Registry['marketplace.marketplace_catalog.vehicles']['types'],
  },
  'marketplace.marketplace_catalog.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace/vehicles/:id',
    tokens: [{"old":"/api/v1/marketplace/vehicles/:id","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/vehicles/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/vehicles/:id","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/vehicles/:id","type":0,"val":"vehicles","end":""},{"old":"/api/v1/marketplace/vehicles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['marketplace.marketplace_catalog.show']['types'],
  },
  'marketplace.marketplace_catalog.availability': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace/vehicles/:id/availability',
    tokens: [{"old":"/api/v1/marketplace/vehicles/:id/availability","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/vehicles/:id/availability","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/vehicles/:id/availability","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/vehicles/:id/availability","type":0,"val":"vehicles","end":""},{"old":"/api/v1/marketplace/vehicles/:id/availability","type":1,"val":"id","end":""},{"old":"/api/v1/marketplace/vehicles/:id/availability","type":0,"val":"availability","end":""}],
    types: placeholder as Registry['marketplace.marketplace_catalog.availability']['types'],
  },
  'marketplace.marketplace_catalog.photo_file': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace/vehicles/:id/photos/:photoId',
    tokens: [{"old":"/api/v1/marketplace/vehicles/:id/photos/:photoId","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/vehicles/:id/photos/:photoId","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/vehicles/:id/photos/:photoId","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/vehicles/:id/photos/:photoId","type":0,"val":"vehicles","end":""},{"old":"/api/v1/marketplace/vehicles/:id/photos/:photoId","type":1,"val":"id","end":""},{"old":"/api/v1/marketplace/vehicles/:id/photos/:photoId","type":0,"val":"photos","end":""},{"old":"/api/v1/marketplace/vehicles/:id/photos/:photoId","type":1,"val":"photoId","end":""}],
    types: placeholder as Registry['marketplace.marketplace_catalog.photo_file']['types'],
  },
  'marketplace.marketplace_review.for_vehicle': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace/vehicles/:id/reviews',
    tokens: [{"old":"/api/v1/marketplace/vehicles/:id/reviews","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/vehicles/:id/reviews","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/vehicles/:id/reviews","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/vehicles/:id/reviews","type":0,"val":"vehicles","end":""},{"old":"/api/v1/marketplace/vehicles/:id/reviews","type":1,"val":"id","end":""},{"old":"/api/v1/marketplace/vehicles/:id/reviews","type":0,"val":"reviews","end":""}],
    types: placeholder as Registry['marketplace.marketplace_review.for_vehicle']['types'],
  },
  'marketplace.marketplace_report.store': {
    methods: ["POST"],
    pattern: '/api/v1/marketplace/reports',
    tokens: [{"old":"/api/v1/marketplace/reports","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/reports","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/reports","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/reports","type":0,"val":"reports","end":""}],
    types: placeholder as Registry['marketplace.marketplace_report.store']['types'],
  },
  'marketplace.marketplace_auth.sync': {
    methods: ["POST"],
    pattern: '/api/v1/marketplace/auth/sync',
    tokens: [{"old":"/api/v1/marketplace/auth/sync","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/auth/sync","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/auth/sync","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/auth/sync","type":0,"val":"auth","end":""},{"old":"/api/v1/marketplace/auth/sync","type":0,"val":"sync","end":""}],
    types: placeholder as Registry['marketplace.marketplace_auth.sync']['types'],
  },
  'marketplace.marketplace_auth.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace/me',
    tokens: [{"old":"/api/v1/marketplace/me","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/me","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/me","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['marketplace.marketplace_auth.me']['types'],
  },
  'marketplace.marketplace_auth.update_profile': {
    methods: ["PATCH"],
    pattern: '/api/v1/marketplace/me',
    tokens: [{"old":"/api/v1/marketplace/me","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/me","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/me","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['marketplace.marketplace_auth.update_profile']['types'],
  },
  'marketplace.marketplace_auth.logout': {
    methods: ["POST"],
    pattern: '/api/v1/marketplace/logout',
    tokens: [{"old":"/api/v1/marketplace/logout","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/logout","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/logout","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['marketplace.marketplace_auth.logout']['types'],
  },
  'marketplace.marketplace_bookings.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace/bookings',
    tokens: [{"old":"/api/v1/marketplace/bookings","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/bookings","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/bookings","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/bookings","type":0,"val":"bookings","end":""}],
    types: placeholder as Registry['marketplace.marketplace_bookings.index']['types'],
  },
  'marketplace.marketplace_bookings.store': {
    methods: ["POST"],
    pattern: '/api/v1/marketplace/bookings',
    tokens: [{"old":"/api/v1/marketplace/bookings","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/bookings","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/bookings","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/bookings","type":0,"val":"bookings","end":""}],
    types: placeholder as Registry['marketplace.marketplace_bookings.store']['types'],
  },
  'marketplace.marketplace_bookings.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace/bookings/:id',
    tokens: [{"old":"/api/v1/marketplace/bookings/:id","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/bookings/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/bookings/:id","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/bookings/:id","type":0,"val":"bookings","end":""},{"old":"/api/v1/marketplace/bookings/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['marketplace.marketplace_bookings.show']['types'],
  },
  'marketplace.marketplace_bookings.cancel': {
    methods: ["POST"],
    pattern: '/api/v1/marketplace/bookings/:id/cancel',
    tokens: [{"old":"/api/v1/marketplace/bookings/:id/cancel","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/bookings/:id/cancel","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/bookings/:id/cancel","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/bookings/:id/cancel","type":0,"val":"bookings","end":""},{"old":"/api/v1/marketplace/bookings/:id/cancel","type":1,"val":"id","end":""},{"old":"/api/v1/marketplace/bookings/:id/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['marketplace.marketplace_bookings.cancel']['types'],
  },
  'marketplace.marketplace_review.store': {
    methods: ["POST"],
    pattern: '/api/v1/marketplace/bookings/:id/reviews',
    tokens: [{"old":"/api/v1/marketplace/bookings/:id/reviews","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/bookings/:id/reviews","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/bookings/:id/reviews","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/bookings/:id/reviews","type":0,"val":"bookings","end":""},{"old":"/api/v1/marketplace/bookings/:id/reviews","type":1,"val":"id","end":""},{"old":"/api/v1/marketplace/bookings/:id/reviews","type":0,"val":"reviews","end":""}],
    types: placeholder as Registry['marketplace.marketplace_review.store']['types'],
  },
  'marketplace.marketplace_favorite.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace/favorites',
    tokens: [{"old":"/api/v1/marketplace/favorites","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/favorites","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/favorites","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/favorites","type":0,"val":"favorites","end":""}],
    types: placeholder as Registry['marketplace.marketplace_favorite.index']['types'],
  },
  'marketplace.marketplace_favorite.ids': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/marketplace/favorites/ids',
    tokens: [{"old":"/api/v1/marketplace/favorites/ids","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/favorites/ids","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/favorites/ids","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/favorites/ids","type":0,"val":"favorites","end":""},{"old":"/api/v1/marketplace/favorites/ids","type":0,"val":"ids","end":""}],
    types: placeholder as Registry['marketplace.marketplace_favorite.ids']['types'],
  },
  'marketplace.marketplace_favorite.store': {
    methods: ["POST"],
    pattern: '/api/v1/marketplace/favorites',
    tokens: [{"old":"/api/v1/marketplace/favorites","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/favorites","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/favorites","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/favorites","type":0,"val":"favorites","end":""}],
    types: placeholder as Registry['marketplace.marketplace_favorite.store']['types'],
  },
  'marketplace.marketplace_favorite.update_notify': {
    methods: ["PATCH"],
    pattern: '/api/v1/marketplace/favorites/:vehicleId',
    tokens: [{"old":"/api/v1/marketplace/favorites/:vehicleId","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/favorites/:vehicleId","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/favorites/:vehicleId","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/favorites/:vehicleId","type":0,"val":"favorites","end":""},{"old":"/api/v1/marketplace/favorites/:vehicleId","type":1,"val":"vehicleId","end":""}],
    types: placeholder as Registry['marketplace.marketplace_favorite.update_notify']['types'],
  },
  'marketplace.marketplace_favorite.destroy': {
    methods: ["DELETE"],
    pattern: '/api/v1/marketplace/favorites/:vehicleId',
    tokens: [{"old":"/api/v1/marketplace/favorites/:vehicleId","type":0,"val":"api","end":""},{"old":"/api/v1/marketplace/favorites/:vehicleId","type":0,"val":"v1","end":""},{"old":"/api/v1/marketplace/favorites/:vehicleId","type":0,"val":"marketplace","end":""},{"old":"/api/v1/marketplace/favorites/:vehicleId","type":0,"val":"favorites","end":""},{"old":"/api/v1/marketplace/favorites/:vehicleId","type":1,"val":"vehicleId","end":""}],
    types: placeholder as Registry['marketplace.marketplace_favorite.destroy']['types'],
  },
  'cities.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/cities',
    tokens: [{"old":"/api/v1/cities","type":0,"val":"api","end":""},{"old":"/api/v1/cities","type":0,"val":"v1","end":""},{"old":"/api/v1/cities","type":0,"val":"cities","end":""}],
    types: placeholder as Registry['cities.index']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
